### ISSUE TITLE
Suggestion: include example error rate in README example

### ISSUE THREAD

**Issue by simonw** [jedisct1/rust-hyperloglog#10]
The example currently looks like this:

https://github.com/jedisct1/rust-hyperloglog/blob/ed1b9b915072ba90c6b93fbfbba30c03215ba682/README.md#L116-L119

```rust
let mut hll = HyperLogLog::new(error_rate);
hll.insert(&"test1");
hll.insert(&"test2");
let card_estimation = hll.len();
```
It would be useful if the `error_rate` there illustrated a sensible default. From looking at the code it seems to be a `f64` - but what is a good value for it?

Should it be `0.01` or `99.9` or something else?

**Comment by jedisct1** [comment]
This is really application-specific.

Is accuracy important? Or does your application need to minimize memory usage?

This is something  to choose on a case by case basis, possibly by running simulation on a sample of actual data.

**Comment by simonw** [comment]
I haven't used HyperLogLog before, so my problem here is that it's asking me to provide a value but not giving me any clues as to how I should pick what that value should be. And I'm not sure how to go about researching the answer - I read the HyperLogLog Wikipedia entry but it didn't help me conclude what would be a good value to use here.

I just tried to answer my question using the new GitHub code search at https://cs.github.com/

https://cs.github.com/?scopeName=All+repos&scope=&q=HyperLogLog%3A%3Anew

<img width="681" alt="image" src="https://user-images.githubusercontent.com/9599/177058778-df85cf70-7744-4943-ab57-2414111f7e1d.png">

I was surprised to see quite a wide range of values in example code:

- 4
- 1 << 8
- 0.174
- 8
- 12
- 0.00408
- 0.001

My hunch from reading about the algorithm is that it would be possible to suggest an example value which would work well-enough for most people who (like me) are too lazy to de deep research and really just want to copy and paste in code from the example in the README.

My goal in using this library is to calculate cardinalities across several million values while using in the order of a few KBs of memory. Is there a good value that would serve that purpose? How could I figure out what that value is?

**Comment by simonw** [comment]
> This is something to choose on a case by case basis, possibly by running simulation on a sample of actual data.

Maybe the README could include an example of how to go about running that kind of simulation?
