### ISSUE TITLE
Crash on error_rate = 0.3 and up

### ISSUE THREAD

**Issue by c4s4** [jedisct1/rust-hyperloglog#13]
This code:

```rust
use hyperloglog::HyperLogLog;

fn main() {
    HyperLogLog::new(0.3);
}
```

Crashes with following error message:

```
assertion failed: (4..=16).contains(&p)
```

This code should work as `error_rate` is supposed to be `< 1.0` and `> 0.0`.

**Comment by jedisct1** [comment]
Such error rate is way too high for the algorithm. I haven't seen values for the alpha constant for `m < 2^4` anywhere.

Semantically, any value in.`]0..1[` is a valid error rate, but then, there are unrelated limitations of the algorithm.
